---
title: "Tarea 2"
author: "Mateo Orozco Baldovino"
format: revealjs
editor: visual
---
**Presentacion**

- Tarea 2: Data Mining
- Nombre: Mateo Orozco Baldovino
- Especialidad en Estadistica Aplicada UTB

**Caracteristicas del entorno de desarrollo:**

- Para el presente trabajo yo agarre el dataset desde este link (https://archive.ics.uci.edu/dataset/222/bank+marketing).

- Estoy realizando el analisis de este dataset usando python en visual studio code y jupyter notebook.

- Para las librerias utilizo un entorno virtual creado con conda.

- Esta tarea puede ser encontrada en este repositorio [Github](https://github.com/TheMaorba/DataMining.git)

- La base de datos utilizada es acerca de una institucion bancaria portuguesa que realizo unas campañas de marketing directo utilizando llamadas telefonicas.

- El objetivo de clasificación es predecir si el cliente suscribirá o no un depósito

- El articulo puede ser encontrado en este link:[Articulo](https://repositorio.iscte-iul.pt/bitstream/10071/9499/5/dss_v3.pdf)

## Punto 1: Descargue y cargue los datos en su notebook, usando Pandas preferiblemente. Imprima para tener una idea de los datos.

```{python}
import respuestas as rp
import pandas as pd
import numpy as np
# Importando la base de datos
df0 = pd.read_csv(r"D:\Documentos\Especialidad\DataMining\Tarea2\Dataset\bank.csv", sep=";")
# Ver tipo de datos en las columnas
df0.dtypes
```
## Punto 2: Calcule la cantidad de datos faltantes y luego si no tiene cree artificialmente datos faltantes.

```{python}
print(f"La cantidad de datos faltantes inicialmente es de: {df0.isna().sum().sum()}")
from faltantes import GestorFaltantes
# Este codigo inserta los datos faltantes o NA y le asigna un nuevo nombre
df_conna = GestorFaltantes.insertar_nans(df0)
# Esta funcion muestra la cantidad de datos faltantes creados en el dataframe
GestorFaltantes.mostrar_nans(df_conna)
"""
En este codigo copio del df original para que no se modifique al momento de realizar los 
cambios
"""
# Para los modelos normales
df1 = df_conna.copy()
# Para KNN
df2 = df_conna.copy()
```
## Punto 3: Use las metodologías vistas en clase para rellenar, o poner, datos en los lugares de los datos faltantes.

All the techniques to handle missing values

- Mean/Median/Mode replacement
- Random Sample Imputation
- Capturing NAN values with a new feature
- End of Distribution Imputation
- Arbitrary Imputation
- Frequent Categories Imputation

### Manejar datos faltantes mediante la eliminacion

```{python}
# Voy a realizar unos cambios para eliminar columnas innecesarias
df1 = df1.drop([
    "housing","day","loan","contact","month", "duration", 
    "campaign", "pdays", "previous", "poutcome", "y"], axis=1)
# Este codigo lo realizo para realizar la eliminacion de los datos faltantes
df_drop = df1.dropna(axis=0)
print(f"La cantidad de datos faltantes actual en la base de datos es de: {df_drop.isna().sum().sum()}")
```
### Manejar datos faltantes imputando datos con un valor fijo o aleatorio

```{python}
# Este codigo crea la columna age_random_fixed
GestorFaltantes.impute_nan_random(df1,"age",1)
print(f"""
      La cantidad de datos faltantes en la nueva columna creada es de: 
      {df1['age_random_fixed'].isna().sum().sum()}
      """)
```


